version: '3.8'

services:
  flask:
    image: scraping-server
    build:
      context: ./scraping
    ports:
      - "5000:5000"

  node:
    image: node-server
    build:
      context: ./servidor
    ports:
      - "3000:3000"
